### PR TITLE
Strip first row

### PR DESCRIPTION
**Pull request by madbuda**
First row contains text, this skips the first row

### CODE REVIEW

**Comment by andrewfraley** [comment]
@madbuda thanks for this, I'll test it out tomorrow.  What version is your SB8200 on and who is your ISP?  Comcast has mine on AB01.01.009.32.01_122319_183.0A.NSH

**Comment by madbuda** [comment]
D31CM-PEREGRINE-1.1.1.0-GA-11-NOSH

WOW not Comcast 

Could be provider/firmware specific 

Here is a snip of the downstream results, as you can see there is a header row  which was causing the failure 

downstream stats: [
{'channel_id': 'Channel ID', 'frequency': 'Frequency', 'power': 'Power', 'snr': 'SNR/MER','corrected': 'Corrected', 'uncorrectables': 'Uncorrectables'},
{'channel_id': '28', 'frequency': '747000000', 'power': '0.4', 'snr': '41.2', 'corrected': '2516', 'uncorrectables': '1439'},
{'channel_id': '1', 'frequency': '609000000', 'power': '0.9', 'snr': '41.9', 'corrected': '510','uncorrectables': '0'},
{'channel_id': '2', 'frequency': '615000000', 'power': '0.0', 'snr': '41.9', 'corrected': '542', 'uncorrectables': '0'},

**Comment by andrewfraley** [comment]
@madbuda could you try the "afraley/fix_7" branch?  https://github.com/andrewfraley/arris_cable_modem_stats/tree/afraley/fix_7

I wanted to fix this in the parse_html_sb8200() function instead of the send_to_influx() function.  Thanks!

**Comment by andrewfraley** [comment]
Merging PR #8 to master.  @madbuda let me know if it ends up not working for you.

**Comment by madbuda** [comment]
Still the same problem
2020-09-05 23:58:56,169 INFO     Sending stats to InfluxDB (influxdb:8086)
Traceback (most recent call last):
  File "arris_stats.py", line 272, in <module>
    main()
  File "arris_stats.py", line 57, in main
    send_to_influx(stats, config)
  File "arris_stats.py", line 219, in send_to_influx
    'frequency': int(stats_up['frequency']),
ValueError: invalid literal for int() with base 10: 'Frequency'

**Pull request closed without merging**
