### PR TITLE
influxdb client to be 2.x

### LINKED ISSUE #35: Does not support new influxdb 2.x client
Hey Andrew:

Current version does not supported the updated 2.x client from Influxdata (https://docs.influxdata.com/influxdb/v2.0/api-guide/client-libraries/python/)

Migration guide here: https://influxdb-client.readthedocs.io/en/stable/migration.html

Breaking Change: the 2.x client requires token based auth so the username/password and a few other options will require adjustment

PR incoming for changes.

### PR DESCRIPTION
**Pull request by cbschuld**
## updates / modifications
influxdb client to the latest 2.x
python image to 3.10-alpine (unnecessary maintenance)
write modes changed to use the updated client calls

## breaking changes in settings
influx_host, influx_database, influx_port, influx_username, influx_password and influx_use_ssl are *dropped*
influx_org, influx_url, influx_bucket and influx_token *added*

also fixes #35

### CODE REVIEW

**Comment by andrewfraley** [comment]
@cbschuld Thank you for this!  I was planning on adding support for InfluxDB 2.x as a separate storage provider so folks could continue to use Influx 1.x, myself included as I'm not ready to switch all my other integrations yet.  Sometime soon I'll take a look a look at this and see what we can do.  For now I'll leave this PR open so they can use your fork if they want immediate 2.x support.  Thanks!

**Comment by cbschuld** [comment]
@andrewfraley makes sense; happy to help with that as well

**Comment by andrewfraley** [comment]
Added support for InfluxDB 2.x in [release v1.6.0](https://github.com/andrewfraley/arris_cable_modem_stats/releases/tag/v1.6.0). @cbschuld thanks for the original PR for this. I implemented it so that we could support both 1.x and 2.x, but used some of your code for arris_stats_influx2.py. Thanks!

**Comment by cbschuld** [comment]
you are welcome Andrew; thanks for the kudos

**Pull request closed without merging**
