### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by DevinCampbell**
Change Docker container example instructions to: docker build -t arris_stats https://github.com/andrewfraley/arris_cable_modem_stats

### CODE REVIEW

**Comment by DevinCampbell** [comment]
I think this is more intuitive to unexperienced users so they don't have to download the files locally.

**Comment by andrewfraley** [comment]
Thanks, Devin!  Anyone using this does need the files local, however, as they need to change config.ini.  I should make this more clear.  A better approach may be to pull in config overrides (in the python script) from ENV variables, then config.ini changes would not be necessary since the ENV variables could be passed to the container at run time.  

Please let me know if you have any additional input, my docker experience is limited.

**Comment by DevinCampbell** [comment]
Ah, you are right. Yes, passing the config variables to the container at runtime would be perfect and is commonly done. You can look at any of the top Docker containers on DockerHub for examples, but they pretty much all do that.

**Comment by DevinCampbell** [comment]
If you look at this container as an example you can see what I believe is a very intuitive and informative format to use for your container: https://hub.docker.com/r/linuxserver/sonarr. The Linuxserver.io team is generally considered one of the better organizations for building Docker containers, so copying them will have you sitting good.

**Pull request closed without merging**
